# Generated by Django 3.2.19 on 2025-07-14 06:52

from django.db import migrations, models
import employee.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=employee.models.employee_image_file_path),
        ),
    ]
