# Generated by Django 3.2.19 on 2025-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_age', models.IntegerField()),
                ('emp_salary', models.IntegerField()),
                ('emp_position', models.CharField(max_length=20)),
            ],
        ),
    ]
