# Generated by Django 3.2.19 on 2025-04-26 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_salary',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(4), django.core.validators.MinLengthValidator(6)]),
        ),
    ]
